### ISSUE TITLE
Simulatore di lettura coordinate

### ISSUE THREAD

**Issue by alkcxy** [ara-astronomia/AutomazioneTende#17]
Attualmente il simulatore è avviato dal server con il flag -t ma funziona abbastanza male perché blocca il client.

Inoltre sul client è presente un flag simulatore che non viene usato.

Rivedere la logica creando un server che simula thesky separato dal server di AutomazioneTende

**Comment by spider65** [comment]
la flag -t è stata eliminata perchè inutile, cosi come è stata eliminata il flag simulatore sulla gui.
le modifiche sono già state mergiate su master
