### ISSUE TITLE
Usare una sola modalità di configurazione GPIO

### ISSUE THREAD

**Issue by alkcxy** [ara-astronomia/AutomazioneTende#21]
decidere e implementare solo l'utilizzo di BMC o BOARD

**Comment by spider65** [comment]
ELENCO GPIO
GPIO.setmode(GPIO.BOARD)

#controllo uscita relay apertura e chiusura tetto
GPIO.setup(13,GPIO.OUT) #comando motore tetto
GPIO.output(13,GPIO.HIGH) #comando apertura tetto
GPIO.output(13,GPIO.LOW) #comando chiusura tetto

#switch stato tetto
GPIO.setup(7,GPIO.IN,pull_up_down=GPIO.PUD_UP) #controllo stato tetto aperto
GPIO.setup(11,GPIO.IN,pull_up_down=GPIO.PUD_UP) #controllo stato tetto chiuso

#Encoder
encoder West
    clk=12
    dt=16
encoder Est
    clk=18
    dt=22
GPIO.setup(clk, GPIO.IN, pull_up_down=GPIO.PUD_UP)
GPIO.setup(dt, GPIO.IN, pull_up_down=GPIO.PUD_UP)

#motori tende
#motore Est
GPIO.setup(31,GPIO.OUT)
GPIO.setup(33,GPIO.OUT)
GPIO.setup(29,GPIO.OUT)
	
	versi rotazione motore, non è possibile sapere quale dei due comandi sia in chiusura o in apertura fino al test sul 		motore che verrà utilizzato 
	GPIO.output(31,GPIO.HIGH)
	GPIO.output(33,GPIO.LOW)
	GPIO.output(29,GPIO.HIGH)

	GPIO.output(31,GPIO.LOW)
	GPIO.output(33,GPIO.HIGH)
	GPIO.output(29,GPIO.HIGH)

#motore West
GPIO.setup(38,GPIO.OUT)
GPIO.setup(40,GPIO.OUT)
GPIO.setup(36,GPIO.OUT)
	
	versi rotazione motore, non è possibile sapere quale dei due comandi sia in chiusura o in apertura fino al test sul 		motore che verrà utilizzato 
	GPIO.output(38,GPIO.HIGH)
	GPIO.output(40,GPIO.LOW)
	GPIO.output(36,GPIO.HIGH)

        GPIO.output(38,GPIO.LOW)
	GPIO.output(40,GPIO.HIGH)
	GPIO.output(36,GPIO.HIGH
