### ISSUE TITLE
Usare GPIOConfig per gli encoder delle tende

### ISSUE THREAD

**Issue by alkcxy** [ara-astronomia/AutomazioneTende#25]
Inoltre verificare se gli encoder devono rimanere in una classe separata od essere maggiormente integrati con i relativi motori

**Comment by alkcxy** [comment]
Partirei da questa classe, disaccoppiando i motori
https://h3ron.com/post/controllare-motore-dc-con-encoder-con-raspberry-pi/

**Comment by spider65** [comment]
cosa intendi per disaccoppiare i motori?

**Comment by alkcxy** [comment]
in questo contesto significa avere encoder e motori in due classi separate. non saranno del tutto disaccoppiate perché motore è indipendente da encoder ma encoder dipende dal motore.

**Comment by spider65** [comment]
Letto

Il sab 21 dic 2019, 18:35 Alessio Caradossi <notifications@github.com> ha
scritto:
