### ISSUE TITLE
text alert curtains

### ISSUE THREAD

**Issue by spider65** [ara-astronomia/AutomazioneTende#73]
encountered a bug.
the alert message "Attenzione tende aperte" remains displayed even if the situation has been resolved.
test:
1)open roof
2) active curtains,
3)digit alt az for high curtains
4) closed roof
alert message is now displayed
5) park tele
6) deactives curtains
7) closed roof
the message is not delete

**Comment by alkcxy** [comment]
Change in a normal issue. 
We need to remove the old alert system that overrides the canvas and create a new alert message field to alert about:
- one or both curtains in DANGER status
- missing connection with the telescope
- other errors
